baseurl = "http://acmla-acacc.ca/carto2017/"
author = "ACMLA-ACACC"
title = "Carto 2017"
languageCode = "en-us"
theme = "hugof"
enableRobotsTXT = true
SectionPagesMenu = ["main"]
googleAnalytics = "UA-52735236-2"

[params.meta]
description = "The 51st Annual Conference of the Association of Canadian Map Libraries and Archives (ACMLA)"
keywords = "libraries, archives, maps, cartography, data"

[params.hero]
herotitle = "Digital Revolutions | Analog Renaissance"
herodescription = "The 51st Annual Conference of the Association of Canadian Map Libraries and Archives (ACMLA) Conference hosted by Simon Fraser University, Vancouver, British Columbia"
btnblue = "Registration Coming Soon!"
logo = "img/Carto2017header.png"
logo-alt = "Carto 2017 logo"

[params.main]
contentOneTitle = "Call for Papers"
contentOneBody = "The digital revolution has brought about considerable change for both users and stewards of cartographic and geospatial information: Advances in imaging technologies have facilitated a mass digital migration of physical collections; the rise of “born digital” cartographic and geospatial information has transformed how collections are developed and used; and expanding mandates for open scholarship are actively changing the expectations for managing and distributing this information. While this “digital transition” has introduced novel opportunities for gathering, investigating and sharing, it has also presented a variety of new challenges to be addressed. In addition, the expansion of digital collections has not left their analog counterparts obsolete; rather, it has provided an opportunity for critical reflection on the role of physical collections, and their persisting value to research, pedagogy and public engagement. <br><br> At this time, the Carto 2017 conference organizers invite librarians, library staff, archivists, geographic information specialists and other interested individuals to submit proposals for papers, panels and workshops that explore the opportunities and challenges associated with digital and analog collections, and consider the role of each in the future of their professions. <br><br> Topics of interest include (but are not limited to):<br><ul><li>Reflecting on and reimagining the role of physical collections in a progressively digital ecosystem. </li><li> Opportunities and approaches for integrating map collections and archival material into research, public engagement and instruction.</li><li>Approaches, resources and tools that support all stages of cartographic material digitization. </li><li> Realizing the potential of digitized collections by integrating digital materials, contextual information and platforms to improve discovery, access and intelligibility.</li><li> Managing geospatial collections and research data, and addressing challenges associated with using, describing, archiving, preserving and providing access to this information. </li><li> Enhancing the digital experience: Considering the shortcomings of digital immersion and implementing approaches that improve user experience with digital cartographic materials. </li><li> Telling stories with cartographic materials: Approaches and applications to engage and educate audiences in digital and analog formats. Advancing digital approaches: Innovative methods for geospatial data analysis and visualization.</li></ul> Please submit an abstract (250 words) of your proposal in either French or English and brief biography using this submission form (http://bit.ly/2kkq0sP). The deadline for submissions is March 27th, 2017. If you do not receive an acknowledgement of your submission or if you have any questions about the conference, please contact a member of the program committee. <br><br>The members of the program committee are:<br><ul><li>Francine Berish, Queen’s University</li><li>Jason Brodeur, McMaster University</li><li>Sue McKee, University of Calgary</li><li>Andrew Nicholson, University of Toronto Mississauga</li><li>Sarah Simpkin, University of Ottawa</li><li>Wenonah Van Heyst, Brandon University</li></ul>"

[params.footer]
email = "webmaster@acmla-acacc.ca"
copy = "2017 ACMLA-ACACC"

[[menu.main]]
name = "Program"
url = "/program"

[[menu.main]]
name = "Venue"
url = "/venue"

[[menu.main]]
name = "Accommodations"
url = "/accommodations"

[[menu.main]]
name = "Register"
url = "/register"

[[menu.main]]
name = "About"
url = "/about"
